version: '3.9'

services:
  db:
    image: postgres:15
    container_name: tuchanchito-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tuchanchito
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - prisma-network

volumes:
  db_data:

networks:
  prisma-network:
