name: PR Vercel Preview Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  Deploy-Preview:
    needs: Unit-Tests
    runs-on: ubuntu-latest
    environment: Preview
    env:
      VERCEL_ORG_ID: "${{ secrets.VERCEL_ORG_ID }}"
      VERCEL_PROJECT_ID: "${{ secrets.VERCEL_PROJECT_ID }}"
      VERCEL_TOKEN: "${{ secrets.VERCEL_TOKEN }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"

      - name: Build Project Artifacts
        run: vercel build --token="$VERCEL_TOKEN"

      - name: Deploy Project Artifacts to Vercel
        run: echo "DEPLOY_URL=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN)" >> $GITHUB_ENV

      - name: Show Deploy URL
        run: echo "🔗 Preview Deployment URL: $DEPLOY_URL"